const int workoutTypeStart = 7;

/// 与 Android Demo 的 jlrunning_string_array 顺序一致，ID 范围为 7～161。
const List<String> workoutTypeNames = [
  'running',
  'treadmill',
  'outdoor running',
  'riding',
  'swim',
  'walking',
  'mountain climbing',
  'Yoga',
  'spinning bike',
  'basketball',
  'football',
  'badminton',
  'marathon',
  'indoor walking',
  'free exercise',
  'track and field',
  'Physical Training',
  'weightlifting',
  'boxing',
  'jump rope',
  'Climb stairs',
  'ski',
  'skate',
  'roller skating',
  'indoor cycling',
  'Hula Hoop',
  'golf',
  'baseball',
  'dance',
  'pingpong',
  'hockey',
  'Pilates',
  'Taekwondo',
  'Handball',
  'hip-hop',
  'volleyball',
  'tennis',
  'darts',
  'gymnastics',
  'step on',
  'elliptical machine',
  'Zumba',
  'cricket',
  'travel by walking',
  'Aerobic exercise',
  'rowing machine',
  'football',
  'Sit-ups',
  'dumbbell',
  'aerobics',
  'karate',
  'fencing',
  'martial arts',
  'Tai Chi',
  'Frisbee',
  'archery',
  'horse riding',
  'bowling',
  'surf',
  'softball',
  'squash',
  'sailboat',
  'pull-ups',
  'skateboard',
  'trampoline',
  'fishing',
  'pole dance',
  'Square dance',
  'Jazz dance',
  'ballet',
  'disco',
  'tap dance',
  'modern dance',
  'push-up',
  'Scooter',
  'plank',
  'billiards',
  'rock climbing',
  'discus',
  'race',
  'wrestling',
  'high jump',
  'parachute',
  'shot put',
  'long jump',
  'javelin',
  'hammer throw',
  'Squat',
  'Leg press',
  'off-road bike',
  'motocross',
  'Rowing',
  'Crossfit',
  'water bike',
  'kayak',
  'croquet',
  'floor ball',
  'muay thai',
  'jai alai',
  'Tennis (double)',
  'back training',
  'water volleyball',
  'water skiing',
  'climbing machine',
  'HIIT',
  'BODY COMBAT',
  'BODY BALANCE',
  'full body resistance exercise',
  'Taekwondo',
  'BMX',
  'stretch',
  'indoor fitness',
  'flexibility training',
  'upper body training',
  'Lower body training',
  'floor exercise',
  'barbell training',
  'Physical Training',
  'deadlift',
  'burpee',
  'functional training',
  'Waist and abdominal training',
  'table football',
  'hunt',
  'stand up paddle boarding',
  'kayak rafting',
  'motorboat',
  'parkour',
  'ATV',
  'Paragliding',
  'curling',
  'ski board',
  'skis',
  'alpine skiing',
  'cross-country skiing',
  'snowmobile',
  'snowmobile',
  'sled',
  'squash',
  'puck',
  'sepak takraw',
  'water polo',
  'belly dance',
  'ballroom dancing',
  'folk dance',
  'latin dance',
  'judo',
  'kickboxing',
  'fly a kite',
  'tug of war',
  'shuttlecock',
  'kabaddi',
  'racing',
  'pebbles game',
  'tag game',
];

String workoutTypeName(int sportType) {
  final index = sportType - workoutTypeStart;
  if (index < 0 || index >= workoutTypeNames.length) {
    return 'Unknown';
  }
  return workoutTypeNames[index];
}
